// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xhsjtgezcrgyypumzkra.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inhoc2p0Z2V6Y3JneXlwdW16a3JhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ5MDg5OTUsImV4cCI6MjA2MDQ4NDk5NX0.Sbek8uZ_fU3HTwZ38iqfxPULKZSCoi5JkEaphYoNDVg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);